/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#ffb4a4",
        "on-tertiary-fixed-variant": "#574500",
        "tertiary": "#efc200",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#580c00",
        "secondary": "#c6c6c7",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed": "#3d0600",
        "on-primary-fixed-variant": "#8c1800",
        "secondary-container": "#454747",
        "inverse-primary": "#b72301",
        "surface-bright": "#3a3939",
        "on-background": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffe083",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary-container": "#4e3e00",
        "on-secondary-container": "#b4b5b5",
        "background": "#131313",
        "on-error": "#690005",
        "outline": "#ab8982",
        "on-tertiary": "#3c2f00",
        "primary": "#ffb4a4",
        "surface-container-highest": "#353534",
        "surface": "#131313",
        "surface-container": "#201f1f",
        "tertiary-container": "#cea700",
        "primary-container": "#ff5733",
        "outline-variant": "#5b403a",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#ffb4a4",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed": "#ffdad3",
        "on-secondary": "#2f3131",
        "surface-dim": "#131313",
        "on-primary": "#630e00",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#231b00",
        "on-surface-variant": "#e4beb6",
        "error-container": "#93000a",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#eec200",
        "surface-variant": "#353534",
        "on-secondary-fixed-variant": "#454747",
        "surface-container-high": "#2a2a2a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "sans": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit"],
        "headline-md": ["Outfit"],
        "label-md": ["Outfit"],
        "headline-lg": ["Outfit"],
        "display": ["Outfit"],
        "label-sm": ["Outfit"],
        "body-md": ["Outfit"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
